coverage:
  range: 60...100
  round: down
  precision: 2
  notify:
    slack:
      default:
        url: $(codecov-webhook)
        threshold: 1%
        only_pulls: false
        branches: 
          - master
          - develop
